### ISSUE TITLE
About the GT of occlusion map.

### ISSUE THREAD

**Issue by shuluoshu** [tim885/P2ORM#6]
Hi @tim885  @YoungXIAO13  , thanks for your work. One detailed question: how to generate the ground truth for occlusion map? Do you annotate it manually or adopt some certain methods?  In fact,  we want to apply your method on other datasets.

Thank you ~

**Comment by tim885** [comment]
Hi, we generate the pixel-pair occlusion relationship GTs from GT depth&normal map using the method proposed in our paper. You can refer to the function gen_occ_order() in P2ORM/DetectOcclusion/lib/dataset/gen_label_methods.py for more implementation details.
